import Nav from "./Nav Footer/Nav"
import style from "./App.module.css"

export const metadata = {
  title: 'Web nuevo proyecto agosto',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={style.body}>
        <Nav/>
        {children}
      </body>
    </html>
  )
}
